services:
  - type: web
    name: alphajourney
    env: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2

      - key: DATABASE_URL
        sync: false

      - key: FB_ACCESS_TOKEN
        sync: false

      - key: FB_PAGE_ID
        sync: false

      - key: GROQ_API_KEY
        sync: false

      - key: GEMINI_API_KEY
        sync: false

      - key: UNSPLASH_ACCESS_KEY
        sync: false

      - key: PEXELS_API_KEY
        sync: false

      - key: AUTO_LIKE
        value: "true"

      - key: AUTO_COMMENT
        value: "true"

      - key: ENGAGEMENT_DELAY
        value: "5"

      - key: PUBLICATION_HOUR
        value: "19"

      - key: PUBLICATION_MINUTE
        value: "0"

      - key: ENVIRONMENT
        value: production
